# -*- coding: utf-8 -*-
"""Spell_Check

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rWGRSaFcloOB8COkY0GzrRExEdD1bUHD

This file creates a spell check library based on the publicated files.

We take all of the pdfs, extract the text and put them in a big text file.

Using this, we get the check library that is trained on this text file.
"""

#!pip install pyspellchecker
from spellchecker import SpellChecker
from google.cloud import storage

client = storage.Client.create_anonymous_client()
bucket_name="rapporteur-pdfs"
bucket = client.bucket(bucket_name=bucket_name, user_project=None)

client = storage.Client.create_anonymous_client()
# you need to set user_project to None for anonymous access
# If not it will attempt to put egress bill on the project you specify,
# and then you need to be authenticated to that project.

punctuations = ['(',')',';',':','[',']',',', '>', '<']
punctuations = ''.join(punctuations)
tans = '         '
trantab = str.maketrans(punctuations, tans)
all_pdf = ''
for b in bucket.list_blobs():
  url = b.public_url
  raw = parser.from_file(url)
  pdf = raw['content'].replace('\n','').replace('-', '').lower()
  pdf = pdf.translate(trantab)
  pdf = re.sub(r'\d+', '', pdf)
  all_pdf += pdf

text_file = open("Output.txt", "w")
text_file.write(all_pdf)
text_file.close()

spell = SpellChecker(language=None)
spell.word_frequency.load_text_file("Output.txt")
spell.export('Output.txt')